export const studentInfo = [
  {
    id: 1,
    lastName: "Clay",
    firstName: "Evelyn",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    gender: "female",
    dateOfBirth: "01.08.1997",
    email: "e.clay@gmail.com",
    phone: "+31 654 12345",
    location: "Amsterdam, The Netherlands",
  },
  {
    id: 2,
    lastName: "Helsloot",
    firstName: "Aranka",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    gender: "female",
    dateOfBirth: "11.12.1989",
    email: "arankahelsloot@hotmail.com",
    phone: "+31 654 12345",
    location: "Haarlem, The Netherlands",
  },
  {
    id: 3,
    lastName: "Mooij",
    firstName: "Floris",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    gender: "male",
    dateOfBirth: "26.04.1969",
    email: "floris_99@hotmail.com",
    phone: "+31 654 12345",
    location: "Utrecht, The Netherlands",
  },
  {
    id: 4,
    lastName: "de Boer",
    firstName: "Hector",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    gender: "male",
    dateOfBirth: "03.02.2000",
    email: "hector_de_boer@gmail.com",
    phone: "+31 654 12345",
    location: "Zoetermeer, The Netherlands",
  },
  {
    id: 5,
    lastName: "Eelman",
    firstName: "Martina",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    gender: "female",
    dateOfBirth: "12.12.1988",
    email: "meelman@hotmail.com",
    phone: "+31 654 12345",
    location: "Rotterdam, The Netherlands",
  },
  {
    id: 6,
    lastName: "Kishun",
    firstName: "Rahima",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    gender: "female",
    dateOfBirth: "12.04.1991",
    email: "rahima_K@me.com",
    phone: "+31 654 12345",
    location: "Urk, The Netherlands",
  },
  {
    id: 7,
    lastName: "Ruiter",
    firstName: "Sandra",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    gender: "female",
    dateOfBirth: "05.05.1978",
    email: "sandra77@hotmail.com",
    phone: "+31 654 12345",
    location: "Ede, The Netherlands",
  },
  {
    id: 8,
    lastName: "Borger",
    firstName: "Wietske",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    gender: "male",
    dateOfBirth: "13.10.1986",
    email: "BorgerW@hetkantoor.com",
    phone: "+31 654 12345",
    location: "Arnhem, The Netherlands",
  },
  {
    id: 9,
    lastName: "Engelbracht",
    firstName: "Storm",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    gender: "male",
    dateOfBirth: "05.08.1987",
    email: "SEngel@hotmail.nl",
    phone: "+31 654 12345",
    location: "Enschede, The Netherlands",
  },
];
